package lk.ijse.hardware.util.enm;

public enum Route {
    POS,DASHBOARD,DASHBOARD_CENTER,PRODUCT,CATEGORY,SUPPLIER,SUPPLIER_LIST,CUSTOMER,CUSTOMER_LIST,PO,GRN,ADD_ITEM_LIST,ORDER,PAYMENT,WASTAGE,
    PAID_ORDER,USER
}
